name: Export NASA Images

on:
  push:
    branches:
      - main

jobs:
  load_dates:
    runs-on: ubuntu-latest
    outputs:
      dates: ${{ steps.load_dates.outputs.dates }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Load dates from JSON
        id: load_dates
        run: |
          dates=$(jq -r '.dates[]' dates.json | tr '\n' ' ')
          echo "dates=${dates}" >> $GITHUB_OUTPUT

  export_images:
    runs-on: ubuntu-latest
    needs: load_dates
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create cache directory
        run: mkdir -p cache

      - name: Download images
        run: |
          dates="${{ needs.load_dates.outputs.dates }}"  # Obtener las fechas de la salida
          IFS=' ' read -r -a date_array <<< "$dates"  # Convertir a un array
          for date in "${date_array[@]}"; do
            echo "Processing date: $date"
            if [[ ! $date =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
              echo "Invalid date format: $date. Skipping."
              continue
            fi

            if [ -f "cache/${date}.json" ]; then
              echo "Using cached data for date: $date"
              url=$(jq -r '.url' cache/${date}.json)
            else
              response=$(curl -s "https://api.nasa.gov/planetary/apod?api_key=${{ secrets.NASA_API_KEY }}&date=${date}")
              echo "$response" > "cache/${date}.json"
              url=$(echo "$response" | jq -r '.url')
            fi
            
            if [ "$url" != "null" ]; then
              echo "Downloading image from $url"
              mkdir -p images
              curl -s -o "images/img-${date}.jpg" "$url"
            else
              echo "No image found for date: $date"
            fi
          done

      - name: Upload images as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "NASA Images"
          path: images/*
          retention-days: 1
