name: Exportar Imágenes de la NASA

on:
  push:
    branches:
      - main

jobs:
  cargar_fechas:
    runs-on: ubuntu-latest
    outputs:
      fechas: ${{ steps.cargar_fechas.outputs.fechas }}
    steps:
      - name: Revisar el repositorio
        uses: actions/checkout@v4

      - name: Cargar fechas desde JSON
        id: cargar_fechas
        run: |
          fechas=$(jq -r '.dates[]' dates.json | tr '\n' ' ')
          echo "fechas=${fechas}" >> $GITHUB_OUTPUT

  exportar_imagenes:
    runs-on: ubuntu-latest
    needs: cargar_fechas
    steps:
      - name: Revisar el repositorio
        uses: actions/checkout@v4

      - name: Crear directorio de caché
        run: mkdir -p cache

      - name: Descargar imágenes
        run: |
          fechas="${{ needs.cargar_fechas.outputs.fechas }}"  # Obtener las fechas de la salida
          IFS=' ' read -r -a array_fechas <<< "$fechas"  # Convertir a un array
          for fecha in "${array_fechas[@]}"; do
            echo "Procesando fecha: $fecha"
            if [[ ! $fecha =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
              echo "Formato de fecha inválido: $fecha. Saltando."
              continue
            fi

            if [ -f "cache/${fecha}.json" ]; then
              echo "Usando datos en caché para la fecha: $fecha"
              url=$(jq -r '.url' cache/${fecha}.json)
            else
              respuesta=$(curl -s "https://api.nasa.gov/planetary/apod?api_key=${{ secrets.NASA_API_KEY }}&date=${fecha}")
              echo "$respuesta" > "cache/${fecha}.json"
              url=$(echo "$respuesta" | jq -r '.url')
            fi
            
            if [ "$url" != "null" ]; then
              echo "Descargando imagen desde $url"
              mkdir -p images
              curl -s -o "images/img-${fecha}.jpg" "$url"
            else
              echo "No se encontró imagen para la fecha: $fecha"
            fi
          done

      - name: Subir imágenes como artefactos
        uses: actions/upload-artifact@v4
        with:
          name: "Imágenes de la NASA"
          path: images/*
          retention-days: 1
