name: Export NASA Images

on:
  push:
    branches:
      - main

jobs:
  export_images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Load dates from JSON
        id: load_dates
        run: |
          echo "dates=$(jq -c '.dates[]' dates.json)" >> $GITHUB_ENV

      - name: Download images
        run: |
          mkdir -p images
          for date in $dates; do
            echo "Processing date: $date"
            if [ -f "cache/$date.json" ]; then
              echo "Using cached data for date: $date"
              url=$(jq -r '.url' cache/$date.json)
            else
              response=$(curl -s "https://api.nasa.gov/planetary/apod?api_key=${{ secrets.NASA_API_KEY }}&date=$date")
              echo $response > "cache/$date.json"
              url=$(echo $response | jq -r '.url')
            fi
            
            if [ "$url" != "null" ]; then
              echo "Downloading image from $url"
              curl -s -o "images/img-$date.jpg" "$url"
            else
              echo "No image found for date: $date"
            fi
          done

      - name: Upload images as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "NASA Images"
          path: images/*
          retention-days: 1
