name: Exportar Imágenes de la NASA

on:
  push:
    branches:
      - main

jobs:
  cargar_fechas:
    runs-on: ubuntu-latest
    outputs:
      fechas: ${{ steps.cargar_fechas.outputs.fechas }}
    steps:
      - name: Revisar el repositorio
        uses: actions/checkout@v4

      - name: Cargar fechas desde JSON
        id: cargar_fechas
        run: |
          fechas=$(jq -c '.dates' dates.json)
          echo "fechas=${fechas}" >> $GITHUB_OUTPUT

  exportar_imagenes:
    runs-on: ubuntu-latest
    needs: cargar_fechas
    strategy:
      matrix:
        fecha: ${{ fromJson(needs.cargar_fechas.outputs.fechas) }} # Cumple el tercer criterio : Los paralelos deben ser dinámicos, es decir que si hay mas fechas, debe haber mas paralelos
    continue-on-error: true #Cumple el primer criterio de: En caso de que falle un paralelo, los demás deben seguir ejecutandose
    steps:
      - name: Revisar el repositorio
        uses: actions/checkout@v4

      - name: Crear directorio de caché
        run: mkdir -p cache

      - name: Usar caché para la respuesta de la API
        uses: actions/cache@v4
        with:
          path: cache
          key: nasa-api-${{ matrix.fecha }} 
          restore-keys: |
            nasa-api-

      - name: Obtener URL de la imagen #Cumple segundo criterio: El cache debe almacenar la respuesta del API  según la fecha consultada y saltar la consulta al API en caso de encontrar la llave
        id: obtener_url
        run: |
          fecha="${{ matrix.fecha }}"
          echo "Procesando fecha: $fecha"

          cache_file="cache/${fecha}.json"
          if [ -f "$cache_file" ]; then
            echo "Usando datos en caché para la fecha: $fecha"
            url=$(jq -r '.url' "$cache_file")
          else
            echo "Llamando a la API de NASA para la fecha: $fecha"
            response=$(curl -s "https://api.nasa.gov/planetary/apod?api_key=${{ secrets.NASA_API_KEY }}&date=${fecha}")
            echo "$response" > "$cache_file"
            url=$(echo "$response" | jq -r '.url')
          fi
          
          if [ "$url" != "null" ] && [ -n "$url" ]; then
            echo "url=$url" >> $GITHUB_OUTPUT
          else
            echo "No se encontró imagen para la fecha: $fecha"
            exit 0
          fi

      - name: Descargar imagen desde la URL #Cumple el cuarto criterio: Debe buscar y usar un action para la descarga de las imágenes
        run: |
          url="${{ steps.obtener_url.outputs.url }}"
          output_path="images/img-${{ matrix.fecha }}.jpg"
          echo "Descargando imagen desde: $url"

          
          mkdir -p images
          
          # Descargar la imagen
          if [[ -n "$url" ]]; then
            curl -L "$url" -o "$output_path" || {
              echo "Error al descargar la imagen desde $url"
              exit 1
            }
          else
            echo "URL vacía. No se puede descargar la imagen."
            exit 1
          fi

      - name: Subir imágenes como artefactos
        uses: actions/upload-artifact@v4
        with:
          name: "img-${{ matrix.fecha }}"
          path: images/img-${{ matrix.fecha }}.jpg
          retention-days: 1