name: Exportar Imágenes de la NASA

on:
  push:
    branches:
      - main

jobs:
  cargar_fechas:
    runs-on: ubuntu-latest
    outputs:
      fechas: ${{ steps.cargar_fechas.outputs.fechas }}
    steps:
      - name: Revisar el repositorio
        uses: actions/checkout@v4

      - name: Cargar fechas desde JSON
        id: cargar_fechas
        run: |
          fechas=$(jq -c '.dates' dates.json)
          echo "fechas=${fechas}" >> $GITHUB_OUTPUT

  exportar_imagenes:
    runs-on: ubuntu-latest
    needs: cargar_fechas
    strategy:
      matrix:
        fecha: ${{ fromJson(needs.cargar_fechas.outputs.fechas) }} # Los paralelos son dinámicos
    continue-on-error: true # Si falla un paralelo, los demás siguen
    steps:
      - name: Revisar el repositorio
        uses: actions/checkout@v4

      - name: Crear directorio de caché
        run: mkdir -p cache

      - name: Usar caché para la respuesta de la API
        uses: actions/cache@v4
        with:
          path: cache
          key: nasa-api-${{ matrix.fecha }}
          restore-keys: |
            nasa-api-

      - name: Obtener URL de la imagen
        id: obtener_url
        run: |
          fecha="${{ matrix.fecha }}"
          echo "Procesando fecha: $fecha"

          cache_file="cache/${fecha}.json"
          if [ -f "$cache_file" ]; then
            echo "Usando datos en caché para la fecha: $fecha"
            url=$(jq -r '.url' "$cache_file")
          else
            echo "Llamando a la API de NASA para la fecha: $fecha"
            response=$(curl -s "https://api.nasa.gov/planetary/apod?api_key=${{ secrets.NASA_API_KEY }}&date=${fecha}")
            echo "$response" > "$cache_file"
            url=$(echo "$response" | jq -r '.url')
          fi
          
          if [ "$url" != "null" ] && [ -n "$url" ]; then
            echo "url=$url" >> $GITHUB_OUTPUT
          else
            echo "No se encontró imagen para la fecha: $fecha"
            exit 0
          fi

      - name: Download file from URL
        uses: minituff/save-image@v1.4
        with:
          url: ${{ steps.obtener_url.outputs.url }}
          output: images/img-${{ matrix.fecha }}.jpg



      - name: Subir imágenes como artefactos
        uses: actions/upload-artifact@v4
        with:
          name: "img-${{ matrix.fecha }}"
          path: images/img-${{ matrix.fecha }}.jpg
          retention-days: 1
